swagger: '2.0'
info:
  description: API for getting GFE results from raw sequence data
  version: "1.0.0"
  title: GFE Submission API
  # put the contact info for your development or API team
  contact:
    email: mhalagan@nmdp.org

  license:
    name: GNU GENERAL PUBLIC LICENSE
    url: https://www.gnu.org/licenses/lgpl.html

# all paths will be relative to the basePath specified
basePath: /api/v1


paths:
  /gfe:
    post:
      summary: Get GFE
      operationId: getGfe
      description: Get Gene Feature Enumeration (GFE) from sequence and locus
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        required: true
        name: GfeSubmission
        description: Submit raw sequence data
        schema:
          $ref: '#/definitions/GfeSubmission'
      responses:
        200:
          description: GFE Generated
          schema:
            $ref: '#/definitions/Gfe'
        400:
          description: error occured
          schema:
             $ref: '#/definitions/Error'
  /sequence:
    post:
      summary: Get sequence from GFE
      operationId: getSequence
      description: Sequence from Gene Feature Enumeration (GFE)
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        required: true
        name: SequenceSubmission
        description: Submit GFE
        schema:
          $ref: '#/definitions/SequenceSubmission'
      responses:
        200:
          description: Sequence Generated
          schema:
            $ref: '#/definitions/Sequence'
        400:
          description: error occured
          schema:
             $ref: '#/definitions/Error'
  /fasta:
    post:
      summary: Get GFE from fasta file
      operationId: getFasta
      description: Get gene Feature Enumeration (GFE) from fasta file
      consumes:
      - multipart/form-data
      - application/x-www-form-urlencoded
      produces:
      - multipart/form-data
      - application/x-www-form-urlencoded
      parameters:
      - in: body
        required: true
        name: FastaSubmission
        description: Submit fasta file
        schema:
          $ref: '#/definitions/FastaSubmission'
      responses:
        200:
          description: GFE data generated
          schema:
            $ref: '#/definitions/SubjectData'
        400:
          description: error occured
          schema:
             $ref: '#/definitions/Error'
definitions:
  GfeSubmission:
    type: object
    required:
    - locus
    - sequence
    properties:
      locus:
        type: string
        example: HLA-A
      sequence:
        type: string
        example: TCCCCAGACGCCGAGGATGGCCGTCATGGCGCCCCGAACCCTCCTCCTGCTACTCTCGGGGGCCCTGGCCCTGACCCAGACCTGGGCGGGTGAGTGCGGGGTCGGGAGGGAAACCGCCTCTGCGGGGAGAAGCAAGGGGCCCTCCTGGCGGGGGCGCAGGACCGGGGGAGCCGCGCCGGGACGAGGGTCGGGCAGGTCTCAGCCACTGCTCGCCCCCAGGCTCCCACTCCATGAGGTATTTCTTCACATCCGTGTCCCGGCCCGGCCGCGGGGAGCCCCGCTTCATCGCCGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGCCAGAGGATGGAGCCGCGGGCGCCGTGGATAGAGCAGGAGGGGCCGGAGTATTGGGACCAGGAGACACGGAATGTGAAGGCCCAGTCACAGACTGACCGAGTGGACCTGGGGACCCTGCGCGGCTACTACAACCAGAGCGAGGCCGGTGAGTGACCCCGGCCGGGGGCGCAGGTCAGGACCCCTCATCCCCCACGGACGGGCCAGGTCGCCCACAGTCTCCGGGTCCGAGATCCACCCCGAAGCCGCGGGACCCCGAGACCCTTGCCCCGGGAGAGGCCCAGGCGCCTTTACCCGGTTTCATTTTCAGTTTAGGCCAAAAATCCCCCCGGGTTGGTCGGGGCTGGGCGGGGCTCGGGGGACTGGGCTGACCGCGGGGTCGGGGCCAGGTTCTCACACCATCCAGATAATGTATGGCTGCGACGTGGGGTCGGACGGGCGCTTCCTCCGCGGGTACCGGCAGGACGCCTACGACGGCAAGGATTACATCGCCCTGAACGAGGACCTGCGCTCTTGGACCGCGGCGGACATGGCGGCTCAGATCACCAAGCGCAAGTGGGAGGCGGCCCATGAGGCGGAGCAGTTGAGAGCCTACCTGGATGGCACGTGCGTGGAGTGGCTCCGCAGATACCTGGAGAACGGGAAGGAGACGCTGCAGCGCACGGGTACCAGGGGCCACGGGGCGCCTCCCTGATCGCCTGTAGATCTCCCGGGCTGGCCTCCCACAAGGAGGGGAGACAATTGGGACCAACACTAGAATATCACCCTCCCTCTGGTCCTGAGGGAGAGGAATCCTCCTGGGTTCCAGATCCTGTACCAGAGAGTGACTCTGAGGTTCCGCCCTGCTCTCTGACACAATTAAGGGATAAAATCTCTGAAGGAGTGACGGGAAGACGATCCCTCGAATACTGATGAGTGGTTCCCTTTGACACCGGCAGCAGCCTTGGGCCCGTGACTTTTCCTCTCAGGCCTTGTTCTCTGCTTCACACTCAATGTGTGTGGGGGTCTGAGTCCAGCACTTCTGAGTCCCTCAGCCTCCACTCAGGTCAGGACCAGAAGTCGCTGTTCCCTTCTCAGGGAATAGAAGATTATCCCAGGTGCCTGTGTCCAGGCTGGTGTCTGGGTTCTGTGCTCTCTTCCCCATCCCGGGTGTCCTGTCCATTCTCAAGATGGCCACATGCGTGCTGGTGGAGTGTCCCATGACAGATGCAAAATGCCTGAATTTTCTGACTCTTCCCGTCAGACCCCCCCAAGACACATATGACCCACCACCCCATCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGCGGGATGGGGAGGACCAGACCCAGGACACGGAGCTCGTGGAGACCAGGCCTGCAGGGGATGGAACCTTCCAGAAGTGGGCGGCTGTGGTGGTGCCTTCTGGAGAGGAGCAGAGATACACCTGCCATGTGCAGCATGAGGGTCTGCCCAAGCCCCTCACCCTGAGATGGGGTAAGGAGGGAGATGGGGGTGTCATGTCTCTTAGGGAAAGCAGGAGCCTCTCTGGAGACCTTTAGCAGGGTCAGGGCCCCTCACCTTCCCCTCTTTTCCCAGAGCTGTCTTCCCAGCCCACCATCCCCATCGTGGGCATCATTGCTGGCCTGGTTCTCCTTGGAGCTGTGATCACTGGAGCTGTGGTCGCTGCCGTGATGTGGAGGAGGAAGAGCTCAGGTGGAGAAGGGGTGAAGGGTGGGGTCTGAGATTTCTTGTCTCACTGAGGGTTCCAAGCCCCAGCTAGAAATGTGCCCTGTCTCATTACTGGGAAGCACCGTCCACAATCATGGGCCTACCCAGTCTGGGCCCCGTGTGCCAGCACTTACTCTTTTGTAAAGCACCTGTTAAAATGAAGGACAGATTTATCACCTTGATTACGGCGGTGATGGGACCTGATCCCAGCAGTCACAAGTCACAGGGGAAGGTCCCTGAGGACAGACCTCAGGAGGGCTATTGGTCCAGGACCCACACCTGCTTTCTTCATGTTTCCTGATCCCGCCCTGGGTCTGCAGTCACACATTTCTGGAAACTTCTCTGGGGTCCAAGACTAGGAGGTTCCTCTAGGACCTTAAGGCCCTGGCTCCTTTCTGGTATCTCACAGGACATTTTCTTCTCACAGATAGAAAAGGAGGGAGTTACACTCAGGCTGCAAGTAAGTATGAAGGAGGCTGATGCCTGAGGTCCTTGGGATATTGTGTTTGGGAGCCCATGGGGGAGCTCACCCACCTCACAATTCCTCCTCTAGCCACATCTTCTGTGGGATCTGACCAGGTTCTGTTTTTGTTCTACCCCAGGCAGTGACAGTGCCCAGGGCTCTGATGTGTCCCTCACAGCTTGTAAAGGTGAGAGCTTGGAGGACCTAATGTGTGTTGGGTGTTGGGCGGAACAGTGGACACAGCTGTGCTATGGGGTTTCTTTGCATTGGATGTATTGAGCATGCGATGGGCTGTTTAAGGTGTGACCCCTCACTGTGATGGATATGAATTTGTTCATGAATATTTTTTTCTATAGTGTGAGACAGCTGCCTTGTGTGGGACTGAG
      url:
        type: string
        example: http://feature.nmdp-bioinformatics.org
      verbose:
        type: boolean
        example: 1
  Gfe:
    type: object
    required:
    - gfe
    - structure
    properties:
      gfe:
        type: string
        example: HLA-Aw1-1-7-20-10-32-7-1-1-1-6-1-5-3-5-1-0
      structure:
          type: array
          items:
            $ref: '#/definitions/Structure'
  Structure:
    type: object
    required:
    - term
    - rank
    - accession
    - sequence
    - locus
    properties:
      term:
        type: string
        example: exon1
      rank:
        type: integer
        example: 1
      accession:
        type: integer
        example: 1
      sequence:
        type: string
        example: AGTGCCCAGGGCTCTGATGTGTCCCTCACAGCTTGTAAAGGTGAGAGCTTGGAGGACCTAATGTGTGTTGGGTGTTGGGCGGAACAGTGGACACAGCTGTGCTATGGGGTTTCTTTGCATTGGATGTATTGAGCATGCGATGGGCTGTTTAAGGTGTGACCCCTCACTGTGATGGATATGAATTTGTTCATGAATATTTTTTTCTATAGTGTGAGACAGCTGCCTTGTGTGGGACTGAG
      locus:
        type: string
        example: HLA-A
  Error:
    type: object
    required:
    - Message
    properties:
      Message:
        type: string
        example: Sequence not defined
      type:
        type: string
        example: Sequence
      sequence:
        type: string
        example: AGTGCCCAGGGCTCTGATGTGTCCCTCACAGCTTGTAAAGGTGAGAGCTTGGAGGACCTAATGTGTGTTGGGTGTTGGGCGGAACAGTGGACACAGCTGTGCTATGGGGTTTCTTTGCATTGGATGTATTGAGCATGCGATGGGCTGTTTAAGGTGTGACCCCTCACTGTGATGGATATGAATTTGTTCATGAATATTTTTTTCTATAGTGTGAGACAGCTGCCTTGTGTGGGACTGAG
      locus:
        type: string
        example: HLA-A
      file:
        type: string
        example: input.fasta
      log:
          type: array
          items:
            type: string
            example: 
              - "2016/10/31 21:16:58 ERROR> GFE.pm:142 GFE::getGfe - Sequence not defined"
              - "2016/10/31 21:16:58 ERROR> GFE.pm:173 GFE::getGfe - Locus not valid"
  Sequence:
    type: object
    required:
    - sequence
    - version
    properties:
      version:
        type: string
        example: 1.1.0
      sequence:
        type: string
        example: AGTGCCCAGGGCTCTGATGTGTCCCTCACAGCTTGTAAAGGTGAGAGCTTGGAGGACCTAATGTGTGTTGGGTGTTGGGCGGAACAGTGGACACAGCTGTGCTATGGGGTTTCTTTGCATTGGATGTATTGAGCATGCGATGGGCTGTTTAAGGTGTGACCCCTCACTGTGATGGATATGAATTTGTTCATGAATATTTTTTTCTATAGTGTGAGACAGCTGCCTTGTGTGGGACTGAG
      structure:
          type: array
          items:
            $ref: '#/definitions/Structure'      
      log:
          type: array
          items:
            type: string
            example: 
              - "2016/10/31 21:16:58 ERROR> GFE.pm:142 GFE::getGfe - Sequence not defined"
              - "2016/10/31 21:16:58 ERROR> GFE.pm:173 GFE::getGfe - Locus not valid"
  SequenceSubmission:
      type: object
      required:
      - gfe
      - locus
      properties:
        gfe:
          type: string
          example: HLA-Aw1-1-7-20-10-32-7-1-1-1-6-1-5-3-5-1-0
        locus:
          type: string
          example: HLA-A
        retry:
          type: integer
          example: 6
        url:
          type: string
          example: http://feature.nmdp-bioinformatics.org
        verbose:
          type: boolean
          example: 1
        structures:
          type: boolean
          example: 1
  Typing:
    type: object
    required:
       - gfe
    properties:
      aligned:
        type: number
        example: .99
      gfe:
        type: string
        example: HLA-Aw1-1-7-20-10-32-7-1-1-1-6-1-5-3-5-1-0
      imgthla:
        type: string
        example: HLA-A*01:01
      structure:
        type: array
        items:
          $ref: '#/definitions/Structure'
  TypingData:
    type: object
    required:
      - typing
      - locus
    properties:
      locus:
        type: string
        example: HLA-A
      typing:
        type: array
        items:
          $ref: '#/definitions/Typing'
  Subject:
    type: object
    required:
    - id
    - typingData
    properties:
      id:
        type: string
        example: 101021-1
      typingData:
          type: array
          items:
            $ref: '#/definitions/TypingData'
  SubjectData:
    type: object
    required:
    - subjects
    - version
    properties:
      version:
        type: string
        example: 1.1.0
      subjects:
          type: array
          items:
            $ref: '#/definitions/Subject'
      log:
          type: array
          items:
            type: string
            example: 
              - "2016/10/31 21:16:58 ERROR> GFE.pm:142 GFE::getGfe - Sequence not defined"
              - "2016/10/31 21:16:58 ERROR> GFE.pm:173 GFE::getGfe - Locus not valid"
  FastaSubmission:
    type: object
    required:
    - file
    - locus
    properties:
      file:
        type: string
      locus:
        type: string
        example: HLA-A
      retry:
        type: integer
        example: 6
      url:
        type: string
        example: http://feature.nmdp-bioinformatics.org
      verbose:
        type: boolean
        example: 1
      structures:
        type: boolean
        example: 1